Bugfix branch
apache/incubator-hugegraph pull request #1838
Opened 2022-04-20 10:25 UTC by mayelena

fix hugegraph-example/Example checkstyle issue

2022-04-20 11:24 UTC, seagle-yuan requested changes

2022-04-20 11:48 UTC, seagle-yuan commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
we need use [LOG.info(">>>> query all vertices: size {}",size);]

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +        LOG.info(String.format(">>>> query all authors lived {}: {}",
need to remove "String.format(" here

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +        LOG.info(">>>> query vertices by primary-values: {}",
please update alignment of the next line

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +        LOG.info(">>>> query edges of vertex by sort-values: " +
ditto

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +        LOG.info(">>>> queryEdges(id-condition): {}",
ditto

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +            LOG.info(">>>> queryEdges(id-condition): {}",
ditto

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +            LOG.info(">>>> queryEdges(contribution): {}",
ditto

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +                LOG.info(">>>> queryEdges(contribution): {}",
ditto

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example2.java
> +        LOG.info(">>>> query all edges: size=" +
ditto

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example2.java
> +        LOG.info(">>>> query all vertices: size=" +
can we also use "... size={}" style?

2022-04-21 10:53 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example2.java
> +        LOG.info(">>>> query vertex(with props) of edges: " + names);
can we also use "{}" style?

2022-04-22 08:11 UTC, javeme commented on hugegraph-example/src/main/java/com/baidu/hugegraph/example/Example1.java
> +        LOG.info(">>>> query vertices by primary-values: {}",vertexList);
expect a space after ","

2022-04-22 08:20 UTC, javeme approved these changes

2022-04-22 09:49 UTC, seagle-yuan approved these changes

2022-04-24 12:01 UTC, seagle-yuan approved these changes

2022-04-24 12:05 UTC, seagle-yuan approved these changes

2022-04-25 14:39 UTC, imbajin approved these changes

2022-04-25 14:39 UTC, merged