chore: Just check dependencies' license with apache action
apache/incubator-hugegraph pull request #2108
Opened 2023-02-09 11:33 UTC by JackyYangPassion

2023-02-09 12:19 UTC, zyxxoo submitted a review, later dismissed

2023-02-09 12:41 UTC, javeme submitted a review, later dismissed

2023-02-09 13:10 UTC, imbajin requested changes
we should handle or know how to fix the problem before merge it

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/17706099/217821725-dd448e71-91ba-490e-9b2b-50cfb9cc42dc.png">

2023-03-14 10:57 UTC, imbajin commented
and also fix dependency-review by github action

![image](https://user-images.githubusercontent.com/17706099/224980402-e2a5ad8c-87bd-4e0f-93ea-a90de243a2ec.png)

2023-03-14 15:15 UTC, javeme commented on .github/workflows/licence-checker.yml
> +  dependency-license:
can we rename to `check-dependency-license` and also rename `check-license` to `check-source-license`

2023-09-10 04:13 UTC, javeme commented
Is it still in progress?

2023-10-11 05:54 UTC, JackyYangPassion commented
Close the PR first and then submit it if there is progress later.

2023-10-11 05:54 UTC, closed without merging