Improve query performance with HBase
apache/incubator-hugegraph pull request #2178
Opened 2023-03-24 14:01 UTC by JackyYangPassion

fix #2177

2023-03-25 10:47 UTC, javeme submitted a review, later dismissed

2023-03-25 15:02 UTC, imbajin requested changes

2023-03-25 15:02 UTC, imbajin commented on hugegraph-hbase/src/main/java/org/apache/hugegraph/backend/store/hbase/HbaseSessions.java
> +            byte[] endRow = ByteBuffer.allocate(2).putShort(value).array();
not quiet clear with it，could u explain it more？

and for any of the scan query condition，we always add the end-row？

could u give a case for it（before vs after），and check the ci problems

2023-03-27 13:41 UTC, javeme commented on hugegraph-hbase/src/main/java/org/apache/hugegraph/backend/store/hbase/HbaseSessions.java
> +            byte[] endRow = ByteBuffer.allocate(2).putShort(value).array();
can call `increaseOne()`?

2023-04-04 09:13 UTC, imbajin commented on hugegraph-hbase/src/main/java/org/apache/hugegraph/backend/store/hbase/HbaseSessions.java
> +                    .setFilter(new PrefixFilter(prefix));
use one line if ≤ 100

2023-04-17 12:06 UTC, javeme commented on hugegraph-hbase/src/main/java/org/apache/hugegraph/backend/store/hbase/HbaseSessions.java
> +            if (table.equals("g_oe") || table.equals("g_ie")) {
can we add a method `HbaseTables.Edge.isEdgeTable(table)`

2023-04-17 12:06 UTC, javeme commented on hugegraph-hbase/src/main/java/org/apache/hugegraph/backend/store/hbase/HbaseSessions.java
> +                short value = (short) (((startRow[0] << 8) | (startRow[1] & 0xFF)) +1);
can we add some comments for why?

2023-05-18 11:12 UTC, imbajin commented
@JackyYangPassion address this PR?

2023-09-10 03:16 UTC, javeme commented
Is it still in progress?

2023-11-27 11:54 UTC, JackyYangPassion commented
Thank you everyone for reviewing and giving this PR #2364 to fix in the future.

2023-11-27 11:55 UTC, closed without merging